### PR TITLE
Clearing up analysis, explaining thought process

### PR DESCRIPTION
**Pull request by catrionamacleod**

### CODE REVIEW

**Review by Harman-arch — APPROVED** [review]
nice

**Comment by Harman-arch** [comment]
-

**Comment by matthew-brett** [comment]
OK - I've merged this one and fixed up the merge conflict.   Now I hope what will happen is that - Cat - you will see that Git reports that the `.Rmd` file has changed (if you edit and save the notebook), and you should `git add` this file and commit.   Harman - you should do the same as we did in the session - that is - you should a) make sure that you do have the `.Rmd` file in your directory after you've saved the notebook and then b) Remove the `.ipynb` file from your repository with `git rm -f Updated_Asylum_app.ipynb` and c) Add the `.Rmd` file with `git add Updated_Asylum_app.Rmd` and d) `git commit`.

**Comment by catrionamacleod** [comment]
Thanks Matthew. Can I just check, do you mean that I will see the .rmd file will have changed when I next want to edit it and I should only git add and commit the .rmd not .ipynb? Or do I need to do something now to sort it?

**Comment by matthew-brett** [comment]
Yes, that's right - you should find that each time you save the notebook, the `.Rmd` file gets updated.

**Pull request merged**
